# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.content_table = QtWidgets.QTableWidget(self.centralwidget)
        self.content_table.setEnabled(True)
        self.content_table.setGeometry(QtCore.QRect(20, 80, 911, 231))
        self.content_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.content_table.setAccessibleDescription("")
        self.content_table.setAutoFillBackground(False)
        self.content_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.content_table.setObjectName("content_table")
        self.content_table.setColumnCount(0)
        self.content_table.setRowCount(0)
        self.status_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.status_label_2.setGeometry(QtCore.QRect(20, 350, 91, 16))
        self.status_label_2.setObjectName("status_label_2")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.status_label.setObjectName("status_label")
        self.log_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.log_textEdit.setEnabled(True)
        self.log_textEdit.setGeometry(QtCore.QRect(20, 530, 811, 79))
        self.log_textEdit.setReadOnly(True)
        self.log_textEdit.setObjectName("log_textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 500, 95, 25))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.selected_table = QtWidgets.QTableWidget(self.centralwidget)
        self.selected_table.setEnabled(True)
        self.selected_table.setGeometry(QtCore.QRect(20, 370, 911, 131))
        self.selected_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.selected_table.setObjectName("selected_table")
        self.selected_table.setColumnCount(0)
        self.selected_table.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 560, 91, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.version_label = QtWidgets.QLabel(self.layoutWidget)
        self.version_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.version_label.setAutoFillBackground(False)
        self.version_label.setText("")
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 911, 33))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.all_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.all_courses_Button.setObjectName("all_courses_Button")
        self.horizontalLayout_2.addWidget(self.all_courses_Button)
        self.this_term_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.this_term_courses_Button.setObjectName("this_term_courses_Button")
        self.horizontalLayout_2.addWidget(self.this_term_courses_Button)
        self.selected_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.selected_courses_Button.setObjectName("selected_courses_Button")
        self.horizontalLayout_2.addWidget(self.selected_courses_Button)
        self.cross_marjor_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.cross_marjor_courses_Button.setObjectName("cross_marjor_courses_Button")
        self.horizontalLayout_2.addWidget(self.cross_marjor_courses_Button)
        self.public_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.public_courses_Button.setObjectName("public_courses_Button")
        self.horizontalLayout_2.addWidget(self.public_courses_Button)
        self.in_marjor_courses_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.in_marjor_courses_Button.setObjectName("in_marjor_courses_Button")
        self.horizontalLayout_2.addWidget(self.in_marjor_courses_Button)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.search_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.search_lineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(210, 320, 566, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.middle_button_group = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.middle_button_group.setContentsMargins(0, 0, 0, 0)
        self.middle_button_group.setObjectName("middle_button_group")
        self.add_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.add_Button.setObjectName("add_Button")
        self.middle_button_group.addWidget(self.add_Button)
        self.delete_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.delete_Button.setObjectName("delete_Button")
        self.middle_button_group.addWidget(self.delete_Button)
        self.choose_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.choose_Button.setObjectName("choose_Button")
        self.middle_button_group.addWidget(self.choose_Button)
        self.select_to_death_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.select_to_death_Button.setEnabled(False)
        self.select_to_death_Button.setObjectName("select_to_death_Button")
        self.middle_button_group.addWidget(self.select_to_death_Button)
        self.unchoose_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.unchoose_Button.setObjectName("unchoose_Button")
        self.middle_button_group.addWidget(self.unchoose_Button)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.content_table.raise_()
        self.status_label_2.raise_()
        self.status_label.raise_()
        self.log_textEdit.raise_()
        self.label_2.raise_()
        self.selected_table.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 22))
        self.menubar.setObjectName("menubar")
        self.menuj = QtWidgets.QMenu(self.menubar)
        self.menuj.setObjectName("menuj")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.select_action = QtWidgets.QAction(MainWindow)
        self.select_action.setObjectName("select_action")
        self.dis_select_action = QtWidgets.QAction(MainWindow)
        self.dis_select_action.setObjectName("dis_select_action")
        self.menuj.addAction(self.select_action)
        self.menuj.addAction(self.dis_select_action)
        self.menubar.addAction(self.menuj.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fuck_courses"))
        self.status_label_2.setText(_translate("MainWindow", "Selected:"))
        self.status_label.setText(_translate("MainWindow", "Status:"))
        self.label_2.setText(_translate("MainWindow", "log:"))
        self.label_3.setText(_translate("MainWindow", "By Boris"))
        self.all_courses_Button.setText(_translate("MainWindow", "所有课程"))
        self.this_term_courses_Button.setText(_translate("MainWindow", "本学期选课"))
        self.selected_courses_Button.setText(_translate("MainWindow", "已选课程"))
        self.cross_marjor_courses_Button.setText(_translate("MainWindow", "跨专业选课"))
        self.public_courses_Button.setText(_translate("MainWindow", "公选课选课"))
        self.in_marjor_courses_Button.setText(_translate("MainWindow", "专业内选课"))
        self.pushButton.setText(_translate("MainWindow", "查看课表"))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.add_Button.setText(_translate("MainWindow", "↓↓↓"))
        self.delete_Button.setText(_translate("MainWindow", "↑↑↑"))
        self.choose_Button.setText(_translate("MainWindow", "一键选课"))
        self.select_to_death_Button.setText(_translate("MainWindow", "抢十次"))
        self.unchoose_Button.setText(_translate("MainWindow", "一键退课"))
        self.menuj.setTitle(_translate("MainWindow", "Operator"))
        self.select_action.setText(_translate("MainWindow", "选课"))
        self.dis_select_action.setText(_translate("MainWindow", "退课"))

